### ISSUE TITLE
EVMRelayer does "consume" gas

### ISSUE THREAD

**Issue by PoolPirate** [axelarnetwork/axelar-local-dev#53]
When calling `relay` to trigger GMP executions the underlying EVMRelayer class deletes the gas event used to pay for the call.
(Relevant piece of code https://github.com/axelarnetwork/axelar-local-dev/blob/main/src/relay/EvmRelayer.ts#L125)

This breaks the expected behavior of gas being passed along for [two-way-calls](https://docs.axelar.dev/dev/gas-services/pay-gas#two-way-call).

An easy workaround could be to have an optional parameter in `relay` that disables the gas payment check completely

**Comment by npty** [comment]
Fixed https://github.com/axelarnetwork/axelar-local-dev/pull/72
