### ISSUE TITLE
The branch feat/forecaller-service has been deleted.

### ISSUE THREAD

**Issue by ThakerJayam** [axelarnetwork/axelar-local-dev#80]
https://github.com/axelarnetwork/axelar-local-dev/blob/029b9b96bc92332483eec53258d07983a8359ef5/packages/axelar-local-dev/package.json#LL36C1-L36C1

We are referencing branch `feat/forecaller-service` of repository `axelar-cgp-solidity` but as you can see here:

https://github.com/axelarnetwork/axelar-cgp-solidity/pull/160 the branch has been closed and deleted now and this is causing npm install to fail with

`
npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout feat/forecaller-service
npm ERR! error: pathspec 'feat/forecaller-service' did not match any file(s) known to git

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-06-20T19_26_29_124Z-debug-0.log
`

**Comment by benreichman** [comment]
Bumping this for visibility. Can confirm the issue.

**Comment by milapsheth** [comment]
Restored the branch. We'll be making an update soon to switch to using main

**Comment by ThakerJayam** [comment]
I am sorry. Do you mean you restored the `feat/forecaller-service` branch temporarily? Or something else?

I tried to look for it but still can't seem to find it. and npm install still gives the same error.

**Comment by milapsheth** [comment]
@benreichman Fixed. Can you try again?
